### ISSUE TITLE
Update requires in explode namespace

### ISSUE THREAD

**Issue by dgsuarez** [dgsuarez/reruby#16]
Explode creates new files, but never requires them. There are 2 approaches that can be taken:

* Add the requires for the new files in the original one.
* Search for requires for the original, and add after each of those the requires for the new files.

**Comment by dcarral** [comment]
@dgsuarez I'm wondering if you have any thoughts on the convenience on one versus the other approach, on top of my head:

Taking into account the use case where a single file is used to require all the files within a gem, we probably would want to go for the second approach. It would also protect against the removal of that concrete file potentially exploding the test suite.

What do you think?

**Comment by dgsuarez** [comment]
Yeah, I like the 2nd one better as well, it's what I'd expect the tool to do.
