### ISSUE TITLE
Slow/hangs on bigger projects

### ISSUE THREAD

**Issue by dgsuarez** [dgsuarez/reruby#17]
I'm pretty sure this is a consequence of 3db11dc4fd296863f873c6d023175ebb545405d0 (using rak instead of ag). 

On my old spinning disk laptop, on ~5k files, the rak version takes 5 seconds to run rename_const, vs 0.2 seconds for the ag one.

We can check for ag/ack and only use rak as a default. 

Even better would be to remove rak and use something like `find -type f -path "*.rb" -not -path "*/\.*" | xargs grep ...` if ag is not found

**Comment by dcarral** [comment]
Just in case it avoids future confusions: the `ag` -> `rak` change was done @ https://github.com/dgsuarez/reruby/pull/15/commits/a256720561ea3d48200292f35a1524f2696f1343, also part of PR #15.

**Comment by dgsuarez** [comment]
:man_facepalming: yep, copied over wrong hash. Thanks!
